# Generated by Django 6.0.2 on 2026-03-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notificationmodel_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='related_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
