# Generated by Django 6.0.2 on 2026-03-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_communitymodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipmodel',
            name='community_exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershipmodel',
            name='weekly_exp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
