# Generated by Django 6.0.2 on 2026-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_membershipmodel_community_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymodel',
            name='community_exp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
