# Generated by Django 6.0.2 on 2026-03-14 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0004_membershipmodel_community_exp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('exp_reward', models.PositiveIntegerField()),
                ('task_type', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly')], max_length=50)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('completed', 'completed'), ('overdue', 'overdue')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='community.communitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('completed', 'completed'), ('overdue', 'overdue')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskmodel')),
            ],
        ),
    ]
