# Generated by Django 6.0.2 on 2026-03-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('completed', 'completed'), ('overdue', 'overdue')], default='available', max_length=20),
        ),
    ]
