# Generated by Django 6.0.2 on 2026-03-15 20:30

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskmodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinventorymodel',
            name='proof_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='proof_image'),
        ),
        migrations.AddField(
            model_name='taskinventorymodel',
            name='proof_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='taskinventorymodel',
            name='proof_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='proof_video'),
        ),
        migrations.AddField(
            model_name='taskinventorymodel',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskinventorymodel',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('pending', 'pending'), ('completed', 'completed'), ('overdue', 'overdue')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskinventorymodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='task.taskmodel'),
        ),
        migrations.AlterField(
            model_name='taskinventorymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
