# Generated by Django 6.0.2 on 2026-03-12 20:27

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customusermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='avatar',
            field=models.URLField(default=users.models.random_avatar, max_length=100),
        ),
    ]
